title: Ben Zhao
author: Ben Zhao
email: ben@wenbinzhao.com
description: >-
  I build enterprise cloud security software at Okta.
  My team develops the Okta directory which manages millions of users, groups, and their schemas.
  I am proficient in many programming languages and technologies including Java, Python, C++, Spring, Scala, Go/GoLang, and Amazon Web Services (AWS).
baseurl: "/"
url: "https://wenbinzhao.com"
linkedin_username: wenbinzhao
github_username:  wenbenz
gtag_id: G-TY9FT3S957