title: Ben Zhao
author: Ben Zhao
email: ben.zhao@benzhao.dev
description: >-
  I build enterprise cloud security software at Okta.
  My team builds and owns Okta's directory which handles operations against billions of users and groups.
  I am proficient in many programming languages and technologies including Java, Python, C++, Spring, Scala, Go/GoLang, and Amazon Web Services (AWS).
baseurl: "/"
url: "https://benzhao.dev"
linkedin_username: benzhaodev
github_username:  wenbenz
gtag_id: G-TY9FT3S957